name: build onnxruntime wheel

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'
env:
  PACKAGE: onnxruntime
jobs:
  build:
    name: Build onnxruntime ${{ matrix.python }} ${{ matrix.platform }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [loongarch64-abi2.0]
        python: ["cp311", "cp312", "cp313", "cp313t", "cp314", "cp314t"]
        platform: ["manylinux"]
    steps:
      - name: Check if exists
        run: |
          pkg=${{ env.PACKAGE }}

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            version="latest"
          else
            version="${{ github.event.inputs.version }}"
          fi

          python_tag="${{ matrix.python }}"
          platform="${{ matrix.platform }}"
          url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
          upstream_url="https://api.github.com/repos/microsoft/${pkg}/releases/latest"

          if [[ "${version}" == "latest" ]]; then
            version="$(curl -s ${upstream_url} | jq -r '.tag_name')"
          fi

          if curl -Ls ${url} | grep -q ${pkg}-${version#v}-.*${python_tag}-${platform}.*loongarch64; then
            echo "SKIP=true" >> $GITHUB_ENV
            echo "${platform} wheels already exists."
          else
            echo "SKIP=false" >> $GITHUB_ENV
            echo "${platform} wheels not found, continue building"
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Clean workspace
        if: ${{ env.SKIP != 'true' }}
        run: |
          safe-rm -rf * .*

      - name: Download source
        if: ${{ env.SKIP != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: microsoft/${{ env.PACKAGE }}
          ref: ${{ env.VERSION }}
          submodules: true

      - name: Set permissions
        if: ${{ env.SKIP != 'true' }}
        run: |
          mkdir -p wheelhouse build
          chmod 777 wheelhouse build

      - name: Patch source
        if: ${{ env.SKIP != 'true' }}
        run: |
          wget -qO - https://github.com/loong64/onnxruntime/raw/refs/heads/main/patch_loong64.patch | patch -p1
          wget -qO cmake/vcpkg-ports/cpuinfo/patch_cpuinfo_h_for_loong64.patch https://github.com/loong64/pytorch/raw/refs/heads/main/cpuinfo/cpuinfo_loong64.patch
        env:
          HTTPS_PROXY: ${{ secrets.PROXY_URL }}

      - name: Build wheel
        if: ${{ env.SKIP != 'true' }}
        run: |
          mkdir -p "${HOME}/data/build"
          DEVICE=CPU
          BUILD_CONFIG=Release
          DOCKER_SCRIPT_OPTIONS=("-d" "${DEVICE}" "-c" "${BUILD_CONFIG}")
          PYTHON_VERSION=${{ matrix.python }}
          if [ "${PYTHON_VERSION}" = "cp313t" ] || [ "${PYTHON_VERSION}" = "cp314t" ]; then
            PYTHON_VERSION=${PYTHON_VERSION%t}
          fi
          PYTHON_EXES="/opt/python/${PYTHON_VERSION}-${{ matrix.python }}/bin/python"
          if [ "${PYTHON_EXES}" != "" ] ; then
            DOCKER_SCRIPT_OPTIONS+=("-p" "${PYTHON_EXES}")
          fi
          BUILD_EXTR_PAR='--use_binskim_compliant_compile_flags --build_wheel --cmake_extra_defines onnxruntime_BUILD_BENCHMARKS=ON'
          if [ "${BUILD_EXTR_PAR}" != "" ] ; then
            DOCKER_SCRIPT_OPTIONS+=("-x" "${BUILD_EXTR_PAR}")
          fi
          DOCKER_IMAGE="ghcr.io/loong64/onnxruntimecpubuildpythonloongarch64:${{ env.VERSION }}"

          docker run --rm \
            --platform linux/loong64 \
            --volume "$(pwd):/onnxruntime_src" \
            --volume "${HOME}/data/build:/build" \
            -w /onnxruntime_src \
            -e ALLOW_RELEASED_ONNX_OPSET_ONLY=0 \
            "$DOCKER_IMAGE" tools/ci_build/github/linux/build_linux_python_package.sh "${DOCKER_SCRIPT_OPTIONS[@]}"

      - name: Upload wheels
        if: ${{ env.SKIP != 'true' }}
        run: |
          ls wheelhouse/*-${{ matrix.python }}-${{ matrix.platform }}_*.whl || exit 1
          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*-${{ matrix.python }}-${{ matrix.platform }}_*.whl
        env:
          TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
